name: Publicar Documentación

on:
  push:
    branches:
      - main  
jobs:
  build_and_publish_docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar DocFX
      - name: Instalar DocFX
        run: |
          curl -sSL https://github.com/dotnet/docfx/releases/download/v2.64.2/docfx.zip -o docfx.zip
          unzip docfx.zip -d docfx
          chmod +x docfx/docfx

      # 3. Construir la documentación
      - name: Generar documentación con DocFX
        run: |
          ./docfx/docfx build

      # 4. Subir la documentación generada a GitHub Pages
      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  
          publish_branch: gh-pages 
