name: Publicar Documentación

on:
  push:
    branches:
      - main  

jobs:
  build_and_publish_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  

      - name: Instalar DocFX
        run: dotnet tool update -g docfx

      - name: Generar metadata con DocFX
        run: docfx metadata Bank/docfx.json  

      - name: Generar documentación con DocFX
        run: docfx build Bank/docfx.json  

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Bank/_site  
          publish_branch: gh-pages 