name: Publicar Documentación

on:
  push:
    branches:
      - main  

jobs:
  build_and_publish_docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar DocFX
      - name: Instalar DocFX
        run: |
          curl -sSL https://github.com/dotnet/docfx/releases/download/v2.75.1/docfx.zip -o docfx.zip
          unzip docfx.zip -d docfx
          chmod +x docfx/docfx
          ./docfx/docfx --version  # Verificar que DocFX se instaló correctamente

      # 3. Generar la documentación
      - name: Generar documentación con DocFX
        run: |
          ./docfx/docfx build

      # 4. Subir la documentación generada a GitHub Pages
      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  
          publish_branch: gh-pages
